# Generated by Django 5.2.5 on 2025-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Полное имя или псевдоним исполнителя', max_length=255, verbose_name='Имя исполнителя')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'artists',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_artist_name')],
            },
        ),
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(help_text='Название альбома', max_length=255, verbose_name='Название альбома')),
                ('release_year', models.PositiveIntegerField(help_text='Четырёхзначный год выпуска альбома', verbose_name='Год выпуска')),
                ('artist', models.ForeignKey(help_text='Исполнитель, выпустивший альбом', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artistmodel', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'db_table': 'albums',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(help_text='Название музыкальной композиции', max_length=255, verbose_name='Название песни')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'db_table': 'songs',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='idx_song_title')],
            },
        ),
        migrations.CreateModel(
            name='AlbumSongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('track_number', models.PositiveIntegerField(help_text='Порядковый номер песни в альбоме', verbose_name='Номер трека')),
                ('album', models.ForeignKey(help_text='Альбом, в который входит песня', on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='catalog.albummodel', verbose_name='Альбом')),
                ('song', models.ForeignKey(help_text='Песня, включённая в альбом', on_delete=django.db.models.deletion.CASCADE, related_name='song_albums', to='catalog.songmodel', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Трек в альбоме',
                'verbose_name_plural': 'Треки в альбомах',
                'db_table': 'album_songs',
                'ordering': ['album', 'track_number'],
            },
        ),
        migrations.AddIndex(
            model_name='albummodel',
            index=models.Index(fields=['artist'], name='idx_album_artist'),
        ),
        migrations.AddIndex(
            model_name='albummodel',
            index=models.Index(fields=['release_year'], name='idx_album_release_year'),
        ),
        migrations.AddIndex(
            model_name='albumsongmodel',
            index=models.Index(fields=['album', 'track_number'], name='idx_album_track'),
        ),
        migrations.AddConstraint(
            model_name='albumsongmodel',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_album_track_number'),
        ),
        migrations.AddConstraint(
            model_name='albumsongmodel',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='unique_album_song'),
        ),
    ]
