# Generated by Django 5.2.5 on 2025-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_albummodel_options_remove_albummodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albummodel',
            options={'ordering': ['-release_year', 'title'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AddField(
            model_name='albummodel',
            name='title',
            field=models.CharField(default=None, help_text='Название альбома', max_length=255, verbose_name='Название альбома'),
            preserve_default=False,
        ),
    ]
