# Generated by Django 5.2.5 on 2025-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_songmodel_lbums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songmodel',
            name='lbums',
        ),
        migrations.AddField(
            model_name='songmodel',
            name='albums',
            field=models.ManyToManyField(related_name='songs', through='catalog.AlbumSongModel', to='catalog.albummodel'),
        ),
    ]
